/***************************************************************************
 * This file is generated by "buildPages v2.0.1"
 * Do not edit this file, it will be overwritten by the pageBuilder script.
 * The buildPages module is part of the PLibESPV1 project.
 * Build context: ESP-ProjectTemplate
 ***************************************************************************/

/**
 * The System Page with Restart / Reset
 * 
 * @PageBuilder:register(SystemPage,CSystemPage)
 */
class CSystemPage extends CPageHandler {
    constructor(oApp) {
        super("system",EC("#SystemPage"),oApp.Config);
        this._App = oApp;
        this.Transe = new CTranslator();
    }

    async restartDevice() {
        let strAsk = await this.Transe.getKeyData("System.Restart.confirm");
        if (confirm(strAsk ?? "restart ?")) {
            this._App.restartDevice();
            let oDlg = new CWaitDialog({
                title: "i18n:System.Restart.title",
                body: "i18n:System.Restart.waitmsg",
                onFinished: function() { location.href = location.href; }
            });
            oDlg.showModal();
        }
    }

    async resetDevice() {
        let strAsk = await this.Transe.getKeyData("System.Reset.confirm");
        if (confirm(strAsk ?? "reset ?")) {
            this._App.resetDevice();
            let oDlg = new CWaitDialog({
                title: "i18n:System.Reset.title",
                body: "i18n:System.Reset.waitmsg",
                onFinished: function() { location.href = location.href; }
            });
            oDlg.showModal();
        }
    }

    on(pView, oElement) {
        if(Utils.isElement(oElement)) {
            switch(oElement.id) {
                case "restart": this.restartDevice(); break;
                case "reset":   this.resetDevice(); break;
            }
        }
    }
}
/**
 * Represents a WiFi Setting page
 * 
 * @PageBuilder:register(WiFiPage,CWiFiPage) 
 */
class CWiFiPage extends CPageHandler {
    /**
     * 
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        // don't use this, before initialized !
        super("wifi",new CElement("#WiFiPage"),oApp.Config);
        this._App = oApp;
       // this.Translator = new CTranslator();
    }

    /**
     * catch the useWiFiBtn click event from the scan dialog to insert the selected network.
     * @param {CView} pView 
     * @param {HTMLElement} oElement 
     * @param {string} strCmd 
     */
    on(pView,oElement,strCmd) {
        super.on(pView,oElement);
        if(Utils.isElement(oElement)) {
            if(oElement.id == "useWifiBtn") {
                let oSource = pView.selById("scan_ssid");
                let oSelected = oSource.options[oSource.selectedIndex];
                if(oSelected) {
                    pView.sel("[data-cfg = 'ssid']").value  = oSelected.value;
                    pView.sel("[data-cfg = 'bssid']").value = oSelected.bssidvalue; 
                }
                this.closeDialog(pView,oElement);
            } 
            // Close action for modal dialog ?
            if(oElement.dataset.dismiss == "modal")  this.closeDialog(pView,oElement);
        }
        
    }

    /**
     * listen on the web socket message and check if the message is a "ssidlist" message.
     * @param {CView} pView 
     * @param {object} oMsg 
     */
    onSocketMessage(pView, oMsg) {
        if(oMsg && oMsg.data == "ssidlist") {
            this.insertFoundNetworks(oMsg.payload);
        }
    }

    /**
     * display the scan network dialog.
     * @param {CView} pView 
     * @param {HTMLElement} oElement
     */
    showScanDialog(pView,oElement) {
        let oThis = this;
        let oDlg = new CDialog("#scanWiFiDialog", { cancelBtn:true });
        // Reset to scan start....
        try { oDlg.sel(".dialogHeader").dataset.i18n = "WiFi.scan.title"; } catch {}
        try { oDlg.sel("#scan_ssid").innerHTML = ""; } catch {}
        this._App.Translator.translate(oDlg.getBase())
            .then(e => {
                oDlg.showModal();
                oThis._App.sendSocketCommand(DEFAULTS.SCAN_WIFI);
            });
    }

    /**
     * insert the found (scanned) networks into the select element.
     * @param {*} oListOfSSIDs 
     */
    insertFoundNetworks(oListOfSSIDs) {
        let oDlg = new CDialog("#scanWiFiDialog");
        let oSelect = oDlg.sel("#scan_ssid");
        try { oDlg.sel(".dialogHeader").dataset.i18n = "WiFi.scan.titleDone"; } catch {}
        this._App.Translator.translate(oDlg.getBase())
            .then(e => {
                for(let i=0; i < oListOfSSIDs.length; i++) {
                    let x = parseInt(oListOfSSIDs[i].rssi);
                    let nPercent = Math.min(Math.max(2 * (x + 100), 0), 100);
                    let oOpt = document.createElement("option");
                    oOpt.value = oListOfSSIDs[i].ssid;
                    oOpt.bssidvalue = oListOfSSIDs[i].bssid;
                    oOpt.innerHTML = oListOfSSIDs[i].ssid + " (" + nPercent + "%) - " + oListOfSSIDs[i].bssid ;
                    oSelect.appendChild(oOpt);
                }
            });
        
        
    }
}


/**
 * Page Handler class for Backup / Restore Page
 * 
 * @PageBuilder:register(BackupPage,CBackupPage)
 */

class CBackupPage extends CPageHandler {
    constructor(oApp) {
        super("backup",document.getElementById("BackupPage"),oApp.Config)
        this._oApp = oApp;
    }

    /**
     * catch the button click events.
     * @param {*} oContent 
     * @param {*} oElement 
     * @param {*} strCmd 
     */
    on(oContent,oElement,strCmd) {
        super.on(oContent,oElement);
        // Backup requested ? - ask the device for a backup file... (catch the result...)
        if(Utils.isElement(oElement)) {
            switch(oElement.id) {
                case "backupSet": 
                    this._oApp.sendSocketCommand(DEFAULTS.GET_BACKUP_COMMAND);
                    break;
                case "restoreSet": 
                    let oAlert = new CAlertDialog({ title: "i18n:SysCfg.Restore.title"})
                    if ("files" in oElement) {
                        if (oElement.files.length === 0) {
                            oAlert.showModal({ body: "i18n:main.noFileSelected"});
                            // alert("You did not select file to restore!");
                        } else {
                            let oReader = new FileReader();
                            oReader.onload = function() {
                                try {
                                    let oConfigData = JSON.parse(oReader.result);
                                    // Check if structure could be a config file...
                                    if (oConfigData.wifi && oConfigData.wifi.hasOwnProperty("ap_mode")) {
                                        if (confirm("File seems to be valid, do you wish to continue?")) {
                                            this.m_oAPP.WS.sendCommandMessage(RESTORE_BACKUP_COMMAND,"",oConfigData);
                                        }
                                    } else {
                                        oAlert.showModal({body: "i18n:SysCfg.Restore.invalidFile"});
                                        // alert("Not a valid backup file!");
                                    }
                                } catch (e) {
                                    oAlert.showModal({body: "i18n:SysCfg.Restore.invalidFile"});
                                    // alert("Invalid backup file!");
                                return;
                                }
        
                            };
                            oReader.readAsText(oElement.files[0]);
                        }
                    }    
                    break;
            }
        }
    }
    
     /**
     * listen on the socket message and check if the message is a "ssidlist" message.
     * @param {*} pView 
     * @param {*} oMsg 
     */
    onBackupMessageReceived(pView, oMsg) {
        if(oMsg) {
            switch(oMsg.data) {
                case "config":  // A backup request for config received...
                    // Simulate a download click...
                    let oDataObj = oMsg.payload;
                    let strData =  "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(oDataObj, null, 2));
                    let dlAnchorElem = pView.selById("downloadSet");
                    dlAnchorElem.setAttribute("href", strData);
                    dlAnchorElem.setAttribute("download", `${this._oApp.Vars.getValue("prog_name")} - settings.json`);
                    dlAnchorElem.click();
                    break;
            }
        }
    }
}
/**
 * Firmware Download / Install page
 * 
 * @PageBuilder:register(FirmwarePage,CFirmwarePage)
 */
class CFirmwarePage extends CPageHandler {
    _fwInstTime = 30;   // Time needed to install firmware..
    constructor(oApp) {
        super("firmware",EC("#FirmwarePage"),oApp.Config);
        this._App = oApp;
        
    }

    loadPageConfig(pView, pApp) {
        super.loadPageConfig(pView,pApp);
        EC("#fwSelect").on("change",this.onFile.bind(this));
        let strURL = pApp.Settings.getData("app.latest.url");
        fetch(strURL)
            .then((response) => {
                return response.json();
            })
            .then((oRelease) => {
                let oAsset = oRelease.assets[0];
                let oDTCreated = new Date(oAsset.created_at);
                let oDTUpdated = new Date(oAsset.updated_at)
                pView.sel("#Date").textContent = oDTCreated.toLocaleDateString() + " / " + oDTUpdated.toLocaleDateString();
                pView.sel("#Name").textContent = oRelease.name;
                pView.sel("#Version").textContent = oRelease.tag_name;
                pView.sel("#Desc").innerHTML = oRelease.body.replaceAll("\n","<br/>");
                pView.gel("#downloadupdate").attr("href",oAsset.browser_download_url);
                pView.sel("#download").disabled = false;
            })
            .catch(ex => {
            });

    }
    onFile(oEvt) {
        EC("#fwInstall").getBase().disabled = false;
    }

    on(pView, oElement) {
        if(oElement) {
            switch(oElement.id) {

                case 'download':
                    // A firmware download was clicked, trigger the download...
                    pView.sel("#downloadupdate").click();
                    break;

                case 'fwSelect':
                    // A Firnware was selected, enable the install button
                    let oFW = pView.sel('#fwInstall');
                    oFW.disabled = false;
                    break;

                case 'fwInstall':
                    // Install the selected Firmware file
                    
                    // formData.append("bin", pView.sel("#fwSelect").files[0]);
                    
                    let oDlg = new CWaitDialog({
                        title: "installing firmware - please wait",
                        timeOutSecs: this._fwInstTime,
                        onFinished: function() { location.href = location.href; }
                    });
                    oDlg.showModal();
                    let oFile = pView.sel("#fwSelect").files[0];
                    let oFormData = new FormData();
                    oFormData.append("bin", oFile, oFile.name);
                    
                    fetch('/update',{ 
                        method:'POST', 
                        body: oFormData
                    });
                    break;
            }
        }
    }

}
/**
  @PageBuilder:register(StatusPage,CStatusPage)
 */

class CStatusPage extends CPageHandler {
    /**
     * 
     * @param {CAPP} oApp 
     */
    constructor(oApp) {
        // don't use this, before initialized !
        super("status",new CElement("#StatusPage"),oApp.Config);
        this._App = oApp;
       // this.Translator = new CTranslator();
    }

        
    // #region Update Status on a regular base
    disposePage(pView, pApp) {
        super.disposePage(pView, pApp);
        this.RefreshTimer = clearInterval(this.RefreshTimer);
        this.RefreshTimer = null;
    }

    preparePage(pView, pApp) {
        super.preparePage(pView, pApp);
        // Set an interval to refresh the status infos every 5 seconds...
        this.RefreshTimer = setInterval( this.refreshStatus.bind(this, pView, pApp), 5000);
    }
    
    refreshStatus(pView, pApp) {
        pApp.requestActStatus();
    }

    /**
     * Triggered, when a new status message is received from the web socket.
     * @param {CView} pView 
     * @param {CApp} pApp 
     * @returns false to avoid loadPageConfig is called again (!) and the game starts again...
     */
    onUpdateStatusReceived(pView, pApp) {
        this.loadPageConfig(pView, pApp);
        return(false)
    }
    // #endregion




    /**
     * Load the page config...
     * Request an actual status from the device...
     * This will trigger an update message, which will be handled in onUpdate_status_Received.
     * @param {CView} pView 
     * @param {CApp} pApp 
     */
    loadPageConfig(pView, pApp) {
        let oStatus = pApp.DeviceStatus;
       
        // set the root element infos - no prefix...
        this.setConfigValues(pView,oStatus);
        for(let strName in oStatus) {
            let oData = oStatus[strName];
            if(oData && Utils.isObj(oData)) {
                this.setConfigValues(pView,oData,strName);
            }
        }

        let oVars = new CVarTable();
        oVars.setVars(pApp.tVars);
        oVars.setVars(oStatus);
        
        // now the usage bar
        let nAvailableSize = oStatus.flash_size - oStatus.fs_total;
        let nPercentUsed = (oStatus.sketch_size * 100) / nAvailableSize;
        let oUsageBar =  pView.sel("#flashUsage");
        if(oUsageBar) {
            oVars.setVar("flash_used_percent",~~nPercentUsed);
            oVars.setVar("flash_available",nAvailableSize);
            oUsageBar.style.width = nPercentUsed + "%";
            oUsageBar.innerText = ~~(oStatus.sketch_size / 1024) + " KB";
            let oUB = EC(oUsageBar);
            let oTranse = new CTranslator();
            let strI18n = "Status.memOK";
            if(nPercentUsed > 50) {
                oUB.rc("usageOK").ac("usageWarn");
                strI18n = "Status.memWarn";
            } else {
                oUB.ac("usageOK").rc("usageWarn");
            }
            oTranse.translateI18n(strI18n,undefined,oVars)
                .then(str => { 
                    oUB.attr("title",str)
                }
            )
        }
        return(oStatus);
    }

    
}

// Page Handler Registration
function registerPageHandler(pApp) {
    pApp.registerPageHandler("SystemPage",new CSystemPage(pApp));
    pApp.registerPageHandler("WiFiPage",new CWiFiPage(pApp));
    pApp.registerPageHandler("BackupPage",new CBackupPage(pApp));
    pApp.registerPageHandler("FirmwarePage",new CFirmwarePage(pApp));
    pApp.registerPageHandler("StatusPage",new CStatusPage(pApp));
}

// End of Page Handler Registration
